# Generated by Django 4.0.2 on 2022-02-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Ссылку', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
