# Generated by Django 4.0.2 on 2022-03-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_link_full_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Когда ссылка сокращена'),
        ),
    ]
